spring:
  application:
    name: spring-learning

  datasource:
    url: jdbc:mysql://localhost:3306/colet_dev
    username: root
    password: sails@123
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        default_schema: colet_dev

server:
  port: 8080